pub(crate) struct DbConnectionStringKeywords;

/// Uppercase connection string keywords, used when generating a connection string.
impl DbConnectionStringKeywords {
    pub const APPLICATION_INTENT: &'static str = "Application Intent";
    pub const APPLICATION_NAME: &'static str = "Application Name";
    pub const ATTACH_DB_FILENAME: &'static str = "AttachDbFilename";
    pub const ATTESTATION_PROTOCOL: &'static str = "Attestation Protocol";
    pub const AUTHENTICATION: &'static str = "Authentication";
    pub const COLUMN_ENCRYPTION_SETTING: &'static str = "Column Encryption Setting";
    pub const CONNECT_RETRY_COUNT: &'static str = "Connect Retry Count";
    pub const CONNECT_RETRY_INTERVAL: &'static str = "Connect Retry Interval";
    pub const CONNECT_TIMEOUT: &'static str = "Connect Timeout";
    pub const COMMAND_TIMEOUT: &'static str = "Command Timeout";
    pub const CURRENT_LANGUAGE: &'static str = "Current Language";
    pub const DATA_SOURCE: &'static str = "Data Source";
    pub const ENCLAVE_ATTESTATION_URL: &'static str = "Enclave Attestation Url";
    pub const ENCRYPT: &'static str = "Encrypt";
    pub const ENLIST: &'static str = "Enlist";
    pub const FAILOVER_PARTNER: &'static str = "Failover Partner";
    pub const INITIAL_CATALOG: &'static str = "Initial Catalog";
    pub const INTEGRATED_SECURITY: &'static str = "Integrated Security";
    pub const IP_ADDRESS_PREFERENCE: &'static str = "IP Address Preference";
    pub const LOAD_BALANCE_TIMEOUT: &'static str = "Load Balance Timeout";
    pub const MAX_POOL_SIZE: &'static str = "Max Pool Size";
    pub const MIN_POOL_SIZE: &'static str = "Min Pool Size";
    pub const MULTIPLE_ACTIVE_RESULT_SETS: &'static str = "Multiple Active Result Sets";
    pub const MULTI_SUBNET_FAILOVER: &'static str = "Multi Subnet Failover";
    pub const PACKET_SIZE: &'static str = "Packet Size";
    pub const PASSWORD: &'static str = "Password";
    pub const PERSIST_SECURITY_INFO: &'static str = "Persist Security Info";
    pub const POOL_BLOCKING_PERIOD: &'static str = "Pool Blocking Period";
    pub const POOLING: &'static str = "Pooling";
    pub const REPLICATION: &'static str = "Replication";
    pub const TRANSACTION_BINDING: &'static str = "Transaction Binding";
    pub const TRUST_SERVER_CERTIFICATE: &'static str = "Trust Server Certificate";
    pub const TYPE_SYSTEM_VERSION: &'static str = "Type System Version";
    pub const USER_ID: &'static str = "User ID";
    pub const USER_INSTANCE: &'static str = "User Instance";
    pub const WORKSTATION_ID: &'static str = "Workstation ID";
}

/// Lowercase connection string keywords, used for string comparison.
pub(crate) struct DbConnectionStringKeywordsLower;

impl DbConnectionStringKeywordsLower {
    pub const APPLICATION_INTENT: &'static str = "application intent";
    pub const APPLICATION_INTENT_ALT: &'static str = "applicationintent";
    pub const APPLICATION_NAME: &'static str = "application name";
    pub const APPLICATION_NAME_ALT: &'static str = "app";
    pub const ATTACH_DB_FILENAME: &'static str = "attachdbfilename";
    pub const ATTESTATION_PROTOCOL: &'static str = "attestation protocol";
    pub const ATTACH_DB_FILENAME_ALT: &'static str = "initial file name";
    pub const AUTHENTICATION: &'static str = "authentication";
    pub const COLUMN_ENCRYPTION_SETTING: &'static str = "column encryption setting";
    pub const CONNECT_RETRY_COUNT: &'static str = "connect retry count";
    pub const CONNECT_RETRY_COUNT_ALT: &'static str = "connectretrycount";
    pub const CONNECT_RETRY_INTERVAL: &'static str = "connect retry interval";
    pub const CONNECT_RETRY_INTERVAL_ALT: &'static str = "connectretryinterval";
    pub const CONNECT_TIMEOUT: &'static str = "connect timeout";
    pub const CONNECT_TIMEOUT_ALT1: &'static str = "connection timeout";
    pub const CONNECT_TIMEOUT_ALT2: &'static str = "timeout";
    pub const COMMAND_TIMEOUT: &'static str = "command timeout";
    pub const CURRENT_LANGUAGE: &'static str = "current language";
    pub const CURRENT_LANGUAGE_ALT: &'static str = "language";
    pub const DATA_SOURCE: &'static str = "data source";
    pub const DATA_SOURCE_ALT1: &'static str = "addr";
    pub const DATA_SOURCE_ALT2: &'static str = "address";
    pub const DATA_SOURCE_ALT3: &'static str = "network address";
    pub const DATA_SOURCE_ALT4: &'static str = "server";
    pub const ENCLAVE_ATTESTATION_URL: &'static str = "enclave attestation url";
    pub const ENCRYPT: &'static str = "encrypt";
    pub const ENLIST: &'static str = "enlist";
    pub const FAILOVER_PARTNER: &'static str = "failover partner";
    pub const INITIAL_CATALOG: &'static str = "initial catalog";
    pub const INITIAL_CATALOG_ALT: &'static str = "database";
    pub const INTEGRATED_SECURITY: &'static str = "integrated security";
    pub const INTEGRATED_SECURITY_ALT: &'static str = "trusted_connection";
    pub const IP_ADDRESS_PREFERENCE: &'static str = "ip address preference";
    pub const IP_ADDRESS_PREFERENCE_ALT: &'static str = "ipaddresspreference";
    pub const LOAD_BALANCE_TIMEOUT: &'static str = "load balance timeout";
    pub const LOAD_BALANCE_TIMEOUT_ALT: &'static str = "connection lifetime";
    pub const MAX_POOL_SIZE: &'static str = "max pool size";
    pub const MIN_POOL_SIZE: &'static str = "min pool size";
    pub const MULTIPLE_ACTIVE_RESULT_SETS: &'static str = "multiple active result sets";
    pub const MULTIPLE_ACTIVE_RESULT_SETS_ALT: &'static str = "multipleactiveresultsets";
    pub const MULTI_SUBNET_FAILOVER: &'static str = "multi subnet failover";
    pub const MULTI_SUBNET_FAILOVER_ALT: &'static str = "multisubnetfailover";
    pub const PACKET_SIZE: &'static str = "packet size";
    pub const PASSWORD: &'static str = "password";
    pub const PASSWORD_ALT: &'static str = "pwd";
    pub const PERSIST_SECURITY_INFO: &'static str = "persist security info";
    pub const PERSIST_SECURITY_INFO_ALT: &'static str = "persistsecurityinfo";
    pub const POOL_BLOCKING_PERIOD: &'static str = "pool blocking period";
    pub const POOL_BLOCKING_PERIOD_ALT: &'static str = "poolblockingperiod";
    pub const POOLING: &'static str = "pooling";
    pub const REPLICATION: &'static str = "replication";
    pub const TRANSACTION_BINDING: &'static str = "transaction binding";
    pub const TYPE_SYSTEM_VERSION: &'static str = "type system version";
    pub const TRUST_SERVER_CERTIFICATE: &'static str = "trust server certificate";
    pub const TRUST_SERVER_CERTIFICATE_ALT: &'static str = "trustservercertificate";
    pub const USER_INSTANCE: &'static str = "user instance";
    pub const USER_ID: &'static str = "user id";
    pub const USER_ID_ALT1: &'static str = "uid";
    pub const USER_ID_ALT2: &'static str = "user";
    pub const WORKSTATION_ID: &'static str = "workstation id";
    pub const WORKSTATION_ALT_ID: &'static str = "wsid";
}
